<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Asset;

class AssetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assets = [
            [
                'asset_code' => 'FUR-001',
                'name' => 'Executive Office Chair',
                'category' => 'Furniture',
                'brand' => 'Herman Miller',
                'model' => 'Aeron',
                'serial_number' => 'HM-AER-2023-001',
                'purchase_date' => '2023-01-15',
                'purchase_price' => 1200.00,
                'location' => 'Main Office - Floor 1',
                'condition' => 'excellent',
                'status' => 'active',
                'description' => 'Ergonomic office chair with lumbar support',
                'supplier' => 'Office Depot',
                'warranty_until' => '2025-01-15',
                'assigned_to' => 'John Doe',
                'department' => 'Executive',
            ],
            [
                'asset_code' => 'ELE-001',
                'name' => 'Dell OptiPlex 7090',
                'category' => 'Electronics',
                'brand' => 'Dell',
                'model' => 'OptiPlex 7090',
                'serial_number' => 'DL7090-2023-001',
                'purchase_date' => '2023-02-10',
                'purchase_price' => 850.00,
                'location' => 'IT Department',
                'condition' => 'good',
                'status' => 'active',
                'description' => 'Desktop computer with Intel i7 processor',
                'supplier' => 'Dell Technologies',
                'warranty_until' => '2026-02-10',
                'assigned_to' => 'Jane Smith',
                'department' => 'IT',
            ],
            [
                'asset_code' => 'EQU-001',
                'name' => 'Industrial Printer',
                'category' => 'Equipment',
                'brand' => 'HP',
                'model' => 'LaserJet Pro 4300',
                'serial_number' => 'HP-LJ-2023-001',
                'purchase_date' => '2023-03-05',
                'purchase_price' => 2500.00,
                'location' => 'Print Room - Floor 2',
                'condition' => 'good',
                'status' => 'active',
                'description' => 'High-volume laser printer for office use',
                'supplier' => 'HP Inc.',
                'warranty_until' => '2025-03-05',
                'assigned_to' => null,
                'department' => 'Operations',
            ],
            [
                'asset_code' => 'FUR-002',
                'name' => 'Conference Table',
                'category' => 'Furniture',
                'brand' => 'Steelcase',
                'model' => 'Universal Round Table',
                'serial_number' => 'SC-URT-2023-001',
                'purchase_date' => '2023-01-20',
                'purchase_price' => 1800.00,
                'location' => 'Conference Room A',
                'condition' => 'excellent',
                'status' => 'active',
                'description' => '12-person round conference table',
                'supplier' => 'Steelcase',
                'warranty_until' => '2028-01-20',
                'assigned_to' => null,
                'department' => 'Meeting Facilities',
            ],
            [
                'asset_code' => 'VEH-001',
                'name' => 'Company Van',
                'category' => 'Vehicle',
                'brand' => 'Ford',
                'model' => 'Transit Connect',
                'serial_number' => 'FD-TC-2023-001',
                'purchase_date' => '2023-04-12',
                'purchase_price' => 35000.00,
                'location' => 'Parking Lot',
                'condition' => 'good',
                'status' => 'active',
                'description' => 'Delivery van for company operations',
                'supplier' => 'Ford Motor Company',
                'warranty_until' => '2026-04-12',
                'assigned_to' => 'Mike Johnson',
                'department' => 'Logistics',
            ],
            [
                'asset_code' => 'ELE-002',
                'name' => 'Samsung 55" Monitor',
                'category' => 'Electronics',
                'brand' => 'Samsung',
                'model' => 'Odyssey G7',
                'serial_number' => 'SM-OG7-2023-001',
                'purchase_date' => '2023-02-28',
                'purchase_price' => 650.00,
                'location' => 'Design Department',
                'condition' => 'excellent',
                'status' => 'active',
                'description' => '55-inch curved gaming monitor for design work',
                'supplier' => 'Samsung Electronics',
                'warranty_until' => '2025-02-28',
                'assigned_to' => 'Sarah Wilson',
                'department' => 'Design',
            ],
            [
                'asset_code' => 'TOO-001',
                'name' => 'Cordless Drill Set',
                'category' => 'Tools',
                'brand' => 'DeWalt',
                'model' => 'DCD771C2',
                'serial_number' => 'DW-DCD-2023-001',
                'purchase_date' => '2023-05-10',
                'purchase_price' => 120.00,
                'location' => 'Maintenance Room',
                'condition' => 'good',
                'status' => 'active',
                'description' => 'Cordless drill with battery and charger',
                'supplier' => 'Home Depot',
                'warranty_until' => '2025-05-10',
                'assigned_to' => null,
                'department' => 'Maintenance',
            ],
            [
                'asset_code' => 'FUR-003',
                'name' => 'Reception Desk',
                'category' => 'Furniture',
                'brand' => 'IKEA',
                'model' => 'MALM',
                'serial_number' => 'IK-MAL-2023-001',
                'purchase_date' => '2023-01-08',
                'purchase_price' => 450.00,
                'location' => 'Reception Area',
                'condition' => 'fair',
                'status' => 'maintenance',
                'description' => 'White reception desk with drawers',
                'supplier' => 'IKEA',
                'warranty_until' => '2024-01-08',
                'assigned_to' => 'Lisa Brown',
                'department' => 'Reception',
            ],
        ];

        foreach ($assets as $asset) {
            Asset::create($asset);
        }
    }
}
