/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'assets': RouteRecordInfo<'assets', '/assets', Record<never, never>, Record<never, never>>,
    'assets-main': RouteRecordInfo<'assets-main', '/assets-main', Record<never, never>, Record<never, never>>,
    'auth-login': RouteRecordInfo<'auth-login', '/auth/login', Record<never, never>, Record<never, never>>,
    'base-products': RouteRecordInfo<'base-products', '/base-products', Record<never, never>, Record<never, never>>,
    'base-products-base-product-composition-modal': RouteRecordInfo<'base-products-base-product-composition-modal', '/base-products/BaseProductCompositionModal', Record<never, never>, Record<never, never>>,
    'base-products-base-product-modal': RouteRecordInfo<'base-products-base-product-modal', '/base-products/BaseProductModal', Record<never, never>, Record<never, never>>,
    'base-products-base-products-management': RouteRecordInfo<'base-products-base-products-management', '/base-products/BaseProductsManagement', Record<never, never>, Record<never, never>>,
    'base-products-stock-update-modal': RouteRecordInfo<'base-products-stock-update-modal', '/base-products/StockUpdateModal', Record<never, never>, Record<never, never>>,
    'bluetooth-devices-management': RouteRecordInfo<'bluetooth-devices-management', '/bluetooth-devices-management', Record<never, never>, Record<never, never>>,
    'cashier-dashboard': RouteRecordInfo<'cashier-dashboard', '/cashier/dashboard', Record<never, never>, Record<never, never>>,
    'categories-management': RouteRecordInfo<'categories-management', '/categories-management', Record<never, never>, Record<never, never>>,
    'customers-management': RouteRecordInfo<'customers-management', '/customers-management', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'discounts-management': RouteRecordInfo<'discounts-management', '/discounts-management', Record<never, never>, Record<never, never>>,
    'hpp-management': RouteRecordInfo<'hpp-management', '/hpp-management', Record<never, never>, Record<never, never>>,
    'inventory-management': RouteRecordInfo<'inventory-management', '/inventory-management', Record<never, never>, Record<never, never>>,
    'items-management': RouteRecordInfo<'items-management', '/items-management', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'management-bluetooth-devices-management': RouteRecordInfo<'management-bluetooth-devices-management', '/management/bluetooth-devices-management', Record<never, never>, Record<never, never>>,
    'manager-dashboard': RouteRecordInfo<'manager-dashboard', '/manager/dashboard', Record<never, never>, Record<never, never>>,
    'packages-management': RouteRecordInfo<'packages-management', '/packages-management', Record<never, never>, Record<never, never>>,
    'pos': RouteRecordInfo<'pos', '/pos', Record<never, never>, Record<never, never>>,
    'pos-components-cash-drawer-dialog': RouteRecordInfo<'pos-components-cash-drawer-dialog', '/pos/components/CashDrawerDialog', Record<never, never>, Record<never, never>>,
    'pos-components-discount-code-input': RouteRecordInfo<'pos-components-discount-code-input', '/pos/components/DiscountCodeInput', Record<never, never>, Record<never, never>>,
    'pos-components-edit-order-dialog': RouteRecordInfo<'pos-components-edit-order-dialog', '/pos/components/EditOrderDialog', Record<never, never>, Record<never, never>>,
    'pos-components-order-detail-dialog': RouteRecordInfo<'pos-components-order-detail-dialog', '/pos/components/OrderDetailDialog', Record<never, never>, Record<never, never>>,
    'pos-components-payment-dialog': RouteRecordInfo<'pos-components-payment-dialog', '/pos/components/PaymentDialog', Record<never, never>, Record<never, never>>,
    'pos-components-promotion-suggestions': RouteRecordInfo<'pos-components-promotion-suggestions', '/pos/components/PromotionSuggestions', Record<never, never>, Record<never, never>>,
    'pos-components-transaction-history-dialog': RouteRecordInfo<'pos-components-transaction-history-dialog', '/pos/components/TransactionHistoryDialog', Record<never, never>, Record<never, never>>,
    'ppn-management': RouteRecordInfo<'ppn-management', '/ppn-management', Record<never, never>, Record<never, never>>,
    'product-compositions': RouteRecordInfo<'product-compositions', '/product-compositions', Record<never, never>, Record<never, never>>,
    'product-compositions-composition-modal': RouteRecordInfo<'product-compositions-composition-modal', '/product-compositions/CompositionModal', Record<never, never>, Record<never, never>>,
    'product-compositions-product-compositions-management': RouteRecordInfo<'product-compositions-product-compositions-management', '/product-compositions/ProductCompositionsManagement', Record<never, never>, Record<never, never>>,
    'product-items-management': RouteRecordInfo<'product-items-management', '/product-items-management', Record<never, never>, Record<never, never>>,
    'product-recipes-id': RouteRecordInfo<'product-recipes-id', '/product-recipes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'products-management': RouteRecordInfo<'products-management', '/products-management', Record<never, never>, Record<never, never>>,
    'promotions-management': RouteRecordInfo<'promotions-management', '/promotions-management', Record<never, never>, Record<never, never>>,
    'purchases-management': RouteRecordInfo<'purchases-management', '/purchases-management', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'reports': RouteRecordInfo<'reports', '/reports', Record<never, never>, Record<never, never>>,
    'reports-purchases': RouteRecordInfo<'reports-purchases', '/reports/purchases', Record<never, never>, Record<never, never>>,
    'reports-sales': RouteRecordInfo<'reports-sales', '/reports/sales', Record<never, never>, Record<never, never>>,
    'roles': RouteRecordInfo<'roles', '/roles', Record<never, never>, Record<never, never>>,
    'roles-main': RouteRecordInfo<'roles-main', '/roles-main', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'suppliers-management': RouteRecordInfo<'suppliers-management', '/suppliers-management', Record<never, never>, Record<never, never>>,
    'user-management': RouteRecordInfo<'user-management', '/user-management', Record<never, never>, Record<never, never>>,
    'users-parent': RouteRecordInfo<'users-parent', '/users', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'users-main': RouteRecordInfo<'users-main', '/users-main', Record<never, never>, Record<never, never>>,
  }
}
