/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'auth-login': RouteRecordInfo<'auth-login', '/auth/login', Record<never, never>, Record<never, never>>,
    'cashier-dashboard': RouteRecordInfo<'cashier-dashboard', '/cashier/dashboard', Record<never, never>, Record<never, never>>,
    'categories-management': RouteRecordInfo<'categories-management', '/categories-management', Record<never, never>, Record<never, never>>,
    'customers-management': RouteRecordInfo<'customers-management', '/customers-management', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'discounts-management': RouteRecordInfo<'discounts-management', '/discounts-management', Record<never, never>, Record<never, never>>,
    'hpp-management': RouteRecordInfo<'hpp-management', '/hpp-management', Record<never, never>, Record<never, never>>,
    'inventory-management': RouteRecordInfo<'inventory-management', '/inventory-management', Record<never, never>, Record<never, never>>,
    'items-management': RouteRecordInfo<'items-management', '/items-management', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'manager-dashboard': RouteRecordInfo<'manager-dashboard', '/manager/dashboard', Record<never, never>, Record<never, never>>,
    'pos': RouteRecordInfo<'pos', '/pos', Record<never, never>, Record<never, never>>,
    'pos-components-cash-drawer-dialog': RouteRecordInfo<'pos-components-cash-drawer-dialog', '/pos/components/CashDrawerDialog', Record<never, never>, Record<never, never>>,
    'pos-components-discount-code-input': RouteRecordInfo<'pos-components-discount-code-input', '/pos/components/DiscountCodeInput', Record<never, never>, Record<never, never>>,
    'pos-components-edit-order-dialog': RouteRecordInfo<'pos-components-edit-order-dialog', '/pos/components/EditOrderDialog', Record<never, never>, Record<never, never>>,
    'pos-components-order-detail-dialog': RouteRecordInfo<'pos-components-order-detail-dialog', '/pos/components/OrderDetailDialog', Record<never, never>, Record<never, never>>,
    'pos-components-payment-dialog': RouteRecordInfo<'pos-components-payment-dialog', '/pos/components/PaymentDialog', Record<never, never>, Record<never, never>>,
    'pos-components-promotion-suggestions': RouteRecordInfo<'pos-components-promotion-suggestions', '/pos/components/PromotionSuggestions', Record<never, never>, Record<never, never>>,
    'pos-components-transaction-history-dialog': RouteRecordInfo<'pos-components-transaction-history-dialog', '/pos/components/TransactionHistoryDialog', Record<never, never>, Record<never, never>>,
    'ppn-management': RouteRecordInfo<'ppn-management', '/ppn-management', Record<never, never>, Record<never, never>>,
    'product-items-management': RouteRecordInfo<'product-items-management', '/product-items-management', Record<never, never>, Record<never, never>>,
    'product-recipes-id': RouteRecordInfo<'product-recipes-id', '/product-recipes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'products-management': RouteRecordInfo<'products-management', '/products-management', Record<never, never>, Record<never, never>>,
    'promotions-management': RouteRecordInfo<'promotions-management', '/promotions-management', Record<never, never>, Record<never, never>>,
    'purchases-management': RouteRecordInfo<'purchases-management', '/purchases-management', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'suppliers-management': RouteRecordInfo<'suppliers-management', '/suppliers-management', Record<never, never>, Record<never, never>>,
  }
}
